mixed-port: 20171
mode: rule
log-level: info
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - 8.8.8.8
  - 1.1.1.1
proxy-providers:
  submill:
    type: file
    path: nodes/all.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - auto
  - balance
  - DIRECT
- name: auto
  type: url-test
  use:
  - submill
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 20
- name: balance
  type: load-balance
  use:
  - submill
  url: http://www.gstatic.com/generate_204
  interval: 300
  strategy: consistent-hashing
- name: FALLBACK
  type: fallback
  proxies:
  - auto
  - balance
  - DIRECT
rules:
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- MATCH,PROXY
allow-lan: true
bind-address: '*'
